### ISSUE TITLE
Feature:Create local mock config file

### ISSUE THREAD

**Issue by talmz** [sharkio-dev/sharkio#119]
After talking with @idodav we thought about creating a local saving for the mocks. (like saving the sniffers on a json file)
What im gonna do is :
Create a 'mock-file-config'
which is a class that has crud operations for adding mocks to the mock config file.

the way the file will be built is as following:
{
sniffer_id: 'xxx'
mocks [ {mock1}, {mock2}...]
}

**Comment by talmz** [comment]
Hey im creating new class `mockFileConfig`  which is responsible for the mock config file (crud operations)
im thinking about adding `mockFileConfig` as attribute of `snifferManager` because I need access to current sniffers because of the structure of the file :
array of sniffer(only port and name) which each sniffer contains array of mocks.

Im starting to work on this, please lmk if you think i should do it differently.
@idodav @Oferlis

**Comment by idodav** [comment]
Sounds like a good start

**Comment by idodav** [comment]
@talmz did you make any progress with this?

**Comment by talmz** [comment]
@idodav I dont have the time right now to work on this (i think in end of august i will have the time), if you want this to be done sooner look for another assignee =)

**Comment by idodav** [comment]
@talmz thanks for the quick response! I'll update you.

**Comment by Oferlis** [comment]
Hey @talmz I want to take this issue, did you have any progress that might help?

**Comment by talmz** [comment]
Nope 🙁

**Comment by Oferlis** [comment]
Hey @idodav just making sure my plan makes sense:
I will generalize the ConfigLoader interface so it can support the mock config also, and create separate interfaces that will extend ConfigLoader - SnifferConfigLoader and MockConfigLoader since they already have pretty much identical functions (load, add, remove, setIsStarted).

This requires some changes and modifying files, so I wanted to make sure this is a good approach.
Would appreciate your input
